version: '3'
services:
  php:
    image: php:7.2-alpine
    volumes:
      - ./app:/app
      - ./vendor:/vendor
    environment:
      - PHP_ENV
    command: sleep 86400
  composer:
    image: composer:1.4
    volumes:
      - ./:/app
    command: composer install --no-interaction
